export const HELP_MAP = {
  'Nokta Avcısı': {
    goal: 'Algısal + Kavramsal Sanbil (Subitizing)',
    tip: 'L1-L2 (1-5 nokta): Zar desenini bir bakışta tanı. L3-L4 (4-10 nokta): Kanonik alt grupları (5+3 gibi) topla.',
    childInfo: 'Beynin küçük sayıları (1-5) tek bakışta tanıyabilir — buna "algısal sanbil" denir. Daha büyük sayıları ise küçük gruplara ayırarak hızlıca anlarsın: 7 noktayı 5+2 olarak görmek gibi. Bu oyunda her ikisini de öğreneceksin!',
    chapterRef: 'Bölüm 4: Sanbil Becerisinin Rolü',
  },
  'Kaç Parmak?': {
    goal: 'Parmak-Sayı İlişkisi',
    tip: 'Açık parmakları tek bakışta say. 5+kaç fazla olduğunu düşün.',
    childInfo: 'Parmakların sayıları öğrenmek için en iyi araçlarından biri! Bir eli gördüğünde hemen 5 olduğunu bilirsin. Bu oyunda parmaklara bakarak sayıları hızlıca tanımayı öğreneceksin.',
    chapterRef: 'Bölüm 4: Sanbil Becerisinin Rolü',
  },
  'Hafıza Oyunu': {
    goal: 'Sayısal Çalışma Belleği',
    tip: 'Kartların konumlarını hatırla. Aynı sayıları eşleştir.',
    childInfo: 'Beyninde kısa süreli bilgi tutan bir "not defteri" var! Kartları çevirdiğinde nerede ne olduğunu hatırlamaya çalışıyorsun. Bu oyun hafızanı güçlendiriyor.',
    chapterRef: 'Bölüm 9: Bilişsel Beceriler',
  },
  'Gruplama Ustası': {
    goal: 'Kavramsal Sanbil',
    tip: 'Çerçevelerdeki dolu kutuları grupla. 5lik ve 10luk yapıları kullan.',
    childInfo: 'Sayıları gruplar halinde düşünmek işini çok kolaylaştırır! Mesela 8 tane nesneyi 5+3 olarak düşünebilirsin. Bu oyunda beşlik ve onluk çerçevelerle gruplamayı öğreneceksin.',
    chapterRef: 'Bölüm 4: Sanbil Becerisinin Rolü',
  },
  'Parmak Köprüsü': {
    goal: 'Parmak-Sayı Eşlemesi (Finger-Number Mapping)',
    tip: 'Parmaklarını sayıları temsil etmek için kullan. 5+kaç fazla olduğunu düşün. Parmak gnozisi (parmak farkındalığı) aritmetik becerilerin güçlü bir yordayıcısıdır (Noël, 2005).',
    childInfo: 'Parmakların sayıların en eski arkadaşı! İnsanlar binlerce yıldır parmaklarıyla sayıyor. Bu oyunda ekrana doğru sayıda parmakla dokunarak sayılarla parmakların arasında güçlü bir köprü kuracaksın.',
    chapterRef: 'Bölüm 4: Sanbil Becerisinin Rolü',
  },
  'Günlük Sanbil': {
    goal: 'Algısal Sanbil (Günlük Nesneler)',
    tip: 'Nesneler 1-5 arasında kısa süre gösterilir. Saymadan, bir bakışta tanı! Seviye arttıkça gösterim süresi kısalır.',
    childInfo: 'Markette 3 elmayı veya masada 4 tabağı saymadan anlayabilirsin — çünkü beynin 5\'e kadar olan miktarları anında tanıyor! Bu oyunda nesneler kısa süre görünecek; saymaya vaktin yok, bir bakışta bulmalısın.',
    chapterRef: 'Bölüm 4: Sanbil Becerisinin Rolü',
  },
  'Nokta Karşılaştırma': {
    goal: 'Yaklaşık Sayı Sistemi (YSS/ANS)',
    tip: 'Saymadan, sezgisel olarak hangisinde daha çok olduğunu hisset. Bu beceri doğuştan gelen sayı hissinin temelidir (Halberda ve ark., 2008). Weber oranı küçüldükçe zorluk artar.',
    childInfo: 'İki tabaktan hangisinde daha çok kurabiye olduğunu saymadan anlayabilirsin! Bu yetenek doğuştan sende var. Sayılar birbirine yaklaştıkça karar vermek zorlaşır ama pratik yaptıkça daha iyi olursun.',
    chapterRef: 'Bölüm 1: Doğuştan Gelen Matematik',
  },
  'Sayı Ayrıştırma': {
    goal: 'Kavramsal Sanbil (Conceptual Subitizing)',
    tip: 'Büyük kümeleri küçük alt gruplara böl! 8 noktayı 5+3 veya 4+4 olarak görmeyi dene. MacDonald-Wilkins modelinde bu en üst sanbil düzeyidir.',
    childInfo: 'Çok fazla noktayı tek seferde saymak zor, ama onları küçük gruplara ayırırsan çok kolay! Mesela 7 noktayı 4 ve 3 olarak görebilirsin. Bu oyunda bu stratejiyi öğreneceksin.',
    chapterRef: 'Bölüm 4: Sanbil Becerisinin Rolü',
  },
  'Tahmin Kavanozları': {
    goal: 'Nicelik Tahmini (ANS)',
    tip: 'Kümeyi bir bütün olarak gör. Referans noktası kullanarak tahmin et.',
    childInfo: 'Bir kavanoza baktığında içinde tam olarak kaç bilye olduğunu bilmesen de "çok mu az mı" hissedebilirsin! Bu oyunda tahmin gücünü geliştirerek gerçeğe çok yakın sayılar bulmayı öğreneceksin.',
    chapterRef: 'Bölüm 5: Tahmin Becerisi',
  },
  'Sayı Doğrusu': {
    goal: 'Zihinsel Sayı Doğrusu',
    tip: 'Sayının aralıktaki oransal konumunu düşün. Yarıyı referans al.',
    childInfo: 'Sayılar bir çizgi üzerinde sırayla dizilir. 5 sayısı 0 ile 10\'un tam ortasındadır! Bu oyunda sayıların çizgi üzerindeki yerlerini bulmayı öğreneceksin.',
    chapterRef: 'Bölüm 5: Tahmin Becerisi',
  },
  'Yakınlık Tahmini': {
    goal: 'Sayısal Büyüklük Karşılaştırma',
    tip: 'Her iki referansa uzaklığı zihninde karşılaştır.',
    childInfo: 'Bir sayının hangi sayıya daha yakın olduğunu düşünmek çok işe yarar! Mesela 7, 5\'e mi 10\'a mı daha yakın? Bu oyunda bunu hızlıca bulmayı öğreneceksin.',
    chapterRef: 'Bölüm 5: Tahmin Becerisi',
  },
  'Ölçme Tahmini': {
    goal: 'Ölçümsel Tahmin',
    tip: 'Referans nesneyi kullanarak hedefin kaç katı olduğunu düşün.',
    childInfo: 'Bir kalemin uzunluğunu bilirsen masanın ne kadar uzun olduğunu tahmin edebilirsin! Bu oyunda bildiğin ölçüleri kullanarak yeni şeyleri tahmin etmeyi öğreneceksin.',
    chapterRef: 'Bölüm 5: Tahmin Becerisi',
  },
  'Hesaplamalı Tahmin': {
    goal: 'İşlemsel Tahmin',
    tip: 'Sayıları yuvarlayarak yaklaşık sonucu hesapla.',
    childInfo: 'Her zaman tam doğru hesap yapmana gerek yok! Markette 3 tane 9 liralık şey alıyorsan "yaklaşık 30 lira" diye düşünebilirsin. Bu oyunda hızlı tahmin yapma becerisini geliştireceksin.',
    chapterRef: 'Bölüm 5: Tahmin Becerisi',
  },
  'Sayı-Sembol Eşleştirme': {
    goal: 'Sembolik Erişim (ÜKM)',
    tip: 'Sembol (rakam) ile nicelik (miktar) arasında köprü kur.',
    childInfo: 'Bir sayıyı birçok farklı şekilde gösterebilirsin: "3" rakamı, üç nokta, "üç" sözcüğü veya üç parmak — hepsi aynı şey! Bu oyunda aynı sayının farklı yüzlerini eşleştireceksin.',
    chapterRef: 'Bölüm 3: Sembolik Sayı İşleme',
  },
  'Büyük-Küçük': {
    goal: 'Sayısal Büyüklük Temsili',
    tip: 'Sayıların zihinsel sayı doğrusundaki konumlarını karşılaştır.',
    childInfo: 'Bazen büyük yazılmış bir sayı seni kandırabilir! Büyük puntolarla yazılmış "3", küçük yazılmış "7"den büyük değildir. Bu oyunda sayının görünüşüne değil, gerçek değerine odaklanmayı öğreneceksin.',
    chapterRef: 'Bölüm 3: Sembolik Sayı İşleme',
  },
  'Çoklu Gösterim': {
    goal: 'Kodlar Arası Dönüştürme (ÜKM)',
    tip: 'Aynı sayıyı farklı biçimlerde (rakam, nokta, çubuk) tanı.',
    childInfo: 'Beynin sayıları üç farklı şekilde tutar: gördüğün rakamlar, duyduğun sözcükler ve hissettiğin miktarlar. Bu oyunda aynı sayının tüm farklı gösterimlerini tanımayı öğreneceksin.',
    chapterRef: 'Bölüm 2: Üçlü Kodlama Modeli',
  },
  'Kod Çevirici': {
    goal: 'Kodlar Arası Dönüştürme (ÜKM)',
    tip: 'Aynı sayıyı farklı biçimlerde (nokta, rakam, sözcük) tanı. Beynin 3 kod sistemi arasında köprü kur!',
    childInfo: 'Bu oyun beynindeki "çevirmen" gibi! Noktayı görüp rakamı bulacaksın, rakamı görüp sözcüğü seçeceksin. Ne kadar hızlı çeviri yaparsan beynin o kadar güçlenir.',
    chapterRef: 'Bölüm 2: Üçlü Kodlama Modeli',
  },
  'Basamak Değeri': {
    goal: 'Görsel-Sembolik Kod (ÜKM)',
    tip: 'Yüzlük, onluk, birlik gruplarını ayırt ederek sayıyı oluştur.',
    childInfo: '"52" sayısında 5 aslında 50 demek, 2 ise sadece 2! Her rakamın yerine göre değeri değişir. Bu oyunda sayılardaki rakamların gerçek değerini keşfedeceksin.',
    chapterRef: 'Bölüm 3: Sembolik Sayı İşleme',
  },
  '1) Şekli Tanıma': {
    goal: 'Van Hiele Düzey 0: Görselleştirme',
    tip: 'Şeklin bütünsel görünümüne odaklan. Döndürme/boyut değişse de tanı.',
    childInfo: 'Bir üçgen küçük de olsa büyük de olsa, kırmızı da olsa mavi de olsa hep üçgendir! Bu oyunda şekilleri her haliyle tanımayı öğreneceksin.',
    chapterRef: 'Bölüm 6: Geometri Çekirdek Bilgisi',
  },
  '2) Eleman ve Özellikler': {
    goal: 'Van Hiele Düzey 1: Analiz',
    tip: 'Kenar sayısı, açı tipi gibi özelliklere odaklan.',
    childInfo: 'Her şeklin kendine özel özellikleri var! Karenin 4 eşit kenarı ve 4 köşesi vardır. Bu oyunda şekillerin kenarlarını, köşelerini ve açılarını keşfedeceksin.',
    chapterRef: 'Bölüm 7: Sezgiden İspata Geçiş',
  },
  '3) İlişkiler ve Çıkarım': {
    goal: 'Van Hiele Düzey 2: İlişkilendirme',
    tip: 'Şekiller arası ilişkileri düşün. Kare bir dikdörtgen midir?',
    childInfo: 'Her kare aslında özel bir dikdörtgendir! Çünkü karenin de 4 köşesi ve 4 dik açısı vardır. Bu oyunda şekiller arasındaki gizli bağlantıları keşfedeceksin.',
    chapterRef: 'Bölüm 7: Sezgiden İspata Geçiş',
  },
  '4) Yön ve Mesafe': {
    goal: 'Uzamsal Biliş (Büyük Uzay)',
    tip: 'Yönleri ve mesafeleri zihninde canlandır.',
    childInfo: 'Sol, sağ, yukarı, aşağı — yönleri bilmek çok önemli! "Okul evin solunda" veya "park evin yukarısında" diyebilmek için yön kavramını bilmen gerek. Bu oyunda nesnelerin birbirine göre yerlerini bulacaksın.',
    chapterRef: 'Bölüm 6: Geometri Çekirdek Bilgisi',
  },
  '5) Zihinsel Döndürme': {
    goal: 'Uzamsal Görselleştirme (IPS)',
    tip: 'Şekli zihninde döndür. Köşe ve kenar ilişkilerine odaklan. Aynalı olan FARKLIDIR!',
    childInfo: 'Bir şekli elinde çevirmeden, sadece kafanda döndürebilirsin! Bu beceri matematik ve günlük hayatta çok işe yarar. Bu oyunda şekilleri zihninde çevirmeyi öğreneceksin.',
    chapterRef: 'Bölüm 6: Geometri Çekirdek Bilgisi',
  },
  '6) Simetri Aynası': {
    goal: 'Simetri Algısı (Mekânsal İlişkiler)',
    tip: 'Simetri ekseni boyunca her satırın ayna görüntüsünü düşün. Dolu hücreler yer değiştirir!',
    childInfo: 'Bir kelebeğin kanatları birbirinin aynısıdır! Buna simetri denir. Bu oyunda desenleri ayna gibi tamamlamayı öğreneceksin.',
    chapterRef: 'Bölüm 6: Geometri Çekirdek Bilgisi',
  },
  'Komşu Sayılar': {
    goal: 'Sayı Sıralılığı (Ordinalite)',
    tip: 'Sayı doğrusunda bir önce ve bir sonra gelen sayıyı düşün.',
    childInfo: 'Her sayının komşuları vardır! 5\'in komşuları 4 ve 6\'dır. Bu oyunda sayıların sırasını ve komşularını bulacaksın.',
    chapterRef: 'Bölüm 1: Doğuştan Gelen Matematik',
  },
  'Parça-Bütün': {
    goal: 'Parça-Bütün İlişkisi',
    tip: 'Bir sayı hangi parçalara ayrılabilir? Toplamı düşünerek parçaları bul.',
    childInfo: '7 elmayı 3 ve 4 olarak iki tabağa koyabilirsin. Ya da 2 ve 5 olarak! Bir sayı farklı parçalara ayrılabilir ama toplamı hep aynı kalır.',
    chapterRef: 'Bölüm 4: Sanbil Becerisinin Rolü',
  },
  'Toplama Stratejileri': {
    goal: 'Esnek Aritmetik Stratejiler',
    tip: 'Onluğa tamamla, ikiye katla veya kolay parçalara ayır.',
    childInfo: '8+5 zor geliyorsa, önce 8+2=10 yap, sonra kalan 3\'ü ekle: 10+3=13! Toplama yapmanın birçok kolay yolu var ve bu oyunda onları öğreneceksin.',
    chapterRef: 'Bölüm 4: Sanbil Becerisinin Rolü',
  },
  'Bölüşme Zamanı': {
    goal: 'Bölme Kavramı (Eşit Paylaştırma)',
    tip: 'Toplam miktarı eşit gruplara ayırmayı düşün.',
    childInfo: '12 çikolatayı 3 arkadaşına eşit paylaştırmak istersen her birine 4 tane düşer! Bu oyunda eşit paylaştırmayı ve gruplara ayırmayı öğreneceksin.',
    chapterRef: 'Bölüm 4: Sanbil Becerisinin Rolü',
  },
  'Sayı Yürüyüşü': {
    goal: 'Bedenleşmiş Aritmetik (Embodied Arithmetic)',
    tip: 'Sayı doğrusunda fiziksel olarak yürü! Toplama = ileri, çıkarma = geri. Link ve ark. (2013) bu yöntemin toplama performansını artırdığını gösterdi.',
    childInfo: 'Sayı doğrusu üzerinde yürüyerek matematik yapabilirsin! Toplama yaparken ileri, çıkarma yaparken geri adım atarsın. Hareket ederek öğrenmek beyni daha çok çalıştırır.',
    chapterRef: 'Bölüm 1: Doğuştan Gelen Matematik',
  },
  'Sayı Bağları': {
    goal: 'Sayı Ayrıştırma (Number Bonds)',
    tip: 'Bir sayıyı iki parçaya ayır. Parçaların toplamı bütüne eşit olmalı. Örn: 7 = 3+4 = 2+5 = 1+6. Butterworth ve ark. (2011) bu becerinin diskalkuli müdahalesinde temel olduğunu gösterdi.',
    childInfo: 'Her sayının gizli ikilileri vardır! 10 sayısını 6+4, 7+3, 8+2 gibi farklı çiftlere ayırabilirsin. Bu çiftleri bilmek toplama ve çıkarmayı çok kolaylaştırır.',
    chapterRef: 'Bölüm 4: Sanbil Becerisinin Rolü',
  },
  'Çıkarma Stratejileri': {
    goal: 'Esnek Çıkarma Stratejileri',
    tip: 'Farklı stratejiler dene: geriye sayma, onluğa tamamlama veya toplama ile kontrol. Bir strateji zorsa başkasını dene!',
    childInfo: '15-8 zor mu? Farklı yollar dene! 15\'ten 8 geriye say, ya da 8\'den 15\'e kadar ileri say. Bir yol zorsa başka bir yol mutlaka daha kolaydır.',
    chapterRef: 'Bölüm 4: Sanbil Becerisinin Rolü',
  },
  'Geri Sayma': {
    goal: 'Geriye Sayma (Ordinalite)',
    tip: 'Sayı doğrusunda geriye doğru git. Her adımda bir önceki sayıyı düşün. Geri sayma, çıkarma işleminin temelidir.',
    childInfo: 'Roket fırlatmadan önce "10, 9, 8, 7..." diye geri sayarsın! Geri sayabilmek çıkarma yapmayı çok kolaylaştırır. Bu oyunda geriye doğru saymayı pratik edeceksin.',
    chapterRef: 'Bölüm 1: Doğuştan Gelen Matematik',
  },
  'Çarpma Kavramı': {
    goal: 'Tekrarlı Toplama (Çarpma Temeli)',
    tip: 'Eşit grupları say! 3 grup 4 nesne = 4+4+4 = 12. Çarpma, tekrarlı toplamanın kısa yoludur.',
    childInfo: '3 tabakta 4\'er kurabiye varsa toplamda kaç kurabiye var? 4+4+4=12! İşte çarpma böyle çalışır: aynı sayıyı tekrar tekrar toplamak yerine kısa yoldan bulursun.',
    chapterRef: 'Bölüm 4: Sanbil Becerisinin Rolü',
  },
  'Sayısal Bellek': {
    goal: 'Çalışma Belleği (N-Geri Görevi)',
    tip: 'Gösterilen sayıyı hatırla ve bir/iki öncekiyle karşılaştır. Çalışma belleği matematik becerisinin temelidir (Soltanlou ve ark., 2022).',
    childInfo: 'Beyninde kısa süreliğine bilgi tutan bir "tahta" var! Bir sayıyı görüp az önceki sayıyla karşılaştırmak bu tahtayı güçlendirir. Güçlü bir hafıza, matematikte sana süper güç verir.',
    chapterRef: 'Bölüm 9: Bilişsel Beceriler',
  },
  'Sayısal Stroop': {
    goal: 'İnhibisyon (Sayısal Stroop Etkisi)',
    tip: 'Sayının boyutuna aldanma! Fiziksel büyüklük değil, sayısal değer önemli. Otomatik tepkiyi baskıla ve doğru değere odaklan.',
    childInfo: 'Küçük yazılmış "7" büyük yazılmış "3"ten daha büyüktür! Gözlerin seni kandırmaya çalışır ama senin asıl sayının değerine odaklanman gerekir. Bu oyun dikkatini güçlendirir.',
    chapterRef: 'Bölüm 9: Bilişsel Beceriler',
  },
  'Görev Değiştirme': {
    goal: 'Bilişsel Esneklik (Task Switching)',
    tip: 'Kural değişiyor! Toplama ve çıkarma arasında hızlıca geçiş yap. Geçiş maliyetini azaltmak için kuralı her seferinde oku.',
    childInfo: 'Bazen toplaman, bazen çıkarman gerekir ve kurallar aniden değişir! Buna hızlıca uyum sağlamak beynini çok esnek yapar. Bu oyun beyni jimnastik gibi çalıştırır.',
    chapterRef: 'Bölüm 9: Bilişsel Beceriler',
  },
};
