export const HELP_MAP = {
  'Nokta Avcısı': { goal: 'Algısal Sanbil (Subitizing)', tip: 'Saymadan, bir bakışta nokta sayısını tanımaya çalış. Bildiğin desenleri (zar, domino) ara!' },
  'Kaç Parmak?': { goal: 'Parmak-Sayı İlişkisi', tip: 'Açık parmakları tek bakışta say. 5+kaç fazla olduğunu düşün.' },
  'Hafıza Oyunu': { goal: 'Sayısal Çalışma Belleği', tip: 'Kartların konumlarını hatırla. Aynı sayıları eşleştir.' },
  'Gruplama Ustası': { goal: 'Kavramsal Sanbil', tip: 'Çerçevelerdeki dolu kutuları grupla. 5lik ve 10luk yapıları kullan.' },
  'Günlük Sanbil': { goal: 'Günlük Yaşam Sanbili', tip: 'Meyve, çiçek, oyuncak gibi nesneleri saymadan tanı. Günlük nesnelerle pratik yap!' },

  'Tahmin Kavanozları': { goal: 'Nicelik Tahmini (ANS)', tip: 'Kümeyi bir bütün olarak gör. Referans noktası kullanarak tahmin et.' },
  'Sayı Doğrusu': { goal: 'Zihinsel Sayı Doğrusu', tip: 'Sayının aralıktaki oransal konumunu düşün. Yarıyı referans al.' },
  'Yakınlık Tahmini': { goal: 'Sayısal Büyüklük Karşılaştırma', tip: 'Her iki referansa uzaklığı zihninde karşılaştır.' },
  'Ölçme Tahmini': { goal: 'Ölçümsel Tahmin', tip: 'Referans nesneyi kullanarak hedefin kaç katı olduğunu düşün.' },
  'Hesaplamalı Tahmin': { goal: 'İşlemsel Tahmin', tip: 'Sayıları yuvarlayarak yaklaşık sonucu hesapla.' },
  'Sayı-Sembol Eşleştirme': { goal: 'Sembolik Erişim (ÜKM)', tip: 'Sembol (rakam) ile nicelik (miktar) arasında köprü kur.' },
  'Büyük-Küçük': { goal: 'Sayısal Büyüklük Temsili', tip: 'Sayıların zihinsel sayı doğrusundaki konumlarını karşılaştır.' },
  'Çoklu Gösterim': { goal: 'Kodlar Arası Dönüştürme (ÜKM)', tip: 'Aynı sayıyı farklı biçimlerde (rakam, nokta, çubuk) tanı.' },
  'Kod Çevirici': { goal: 'Kodlar Arası Dönüştürme (ÜKM)', tip: 'Aynı sayıyı farklı biçimlerde (nokta, rakam, sözcük) tanı. Beynin 3 kod sistemi arasında köprü kur!' },
  'Basamak Değeri': { goal: 'Görsel-Sembolik Kod (ÜKM)', tip: 'Yüzlük, onluk, birlik gruplarını ayırt ederek sayıyı oluştur.' },
  '1) Şekli Tanıma': { goal: 'Van Hiele Düzey 0: Görselleştirme', tip: 'Şeklin bütünsel görünümüne odaklan. Döndürme/boyut değişse de tanı.' },
  '2) Eleman ve Özellikler': { goal: 'Van Hiele Düzey 1: Analiz', tip: 'Kenar sayısı, açı tipi gibi özelliklere odaklan.' },
  '3) İlişkiler ve Çıkarım': { goal: 'Van Hiele Düzey 2: İlişkilendirme', tip: 'Şekiller arası ilişkileri düşün. Kare bir dikdörtgen midir?' },
  '6) Simetri Aynası': { goal: 'Simetri Algısı (Mekânsal İlişkiler)', tip: 'Simetri ekseni boyunca her satırın ayna görüntüsünü düşün. Dolu hücreler yer değiştirir!' },
  '5) Zihinsel Döndürme': { goal: 'Uzamsal Görselleştirme (IPS)', tip: 'Şekli zihninde döndür. Köşe ve kenar ilişkilerine odaklan. Aynalı olan FARKLIDIR!' },
  '4) Yön ve Mesafe': { goal: 'Uzamsal Biliş (Büyük Uzay)', tip: 'Yönleri ve mesafeleri zihninde canlandır.' },
  'Komşu Sayılar': { goal: 'Sayı Sıralılığı (Ordinalite)', tip: 'Sayı doğrusunda bir önce ve bir sonra gelen sayıyı düşün.' },
  'Parça-Bütün': { goal: 'Parça-Bütün İlişkisi', tip: 'Bir sayı hangi parçalara ayrılabilir? Toplamı düşünerek parçaları bul.' },
  'Toplama Stratejileri': { goal: 'Esnek Aritmetik Stratejiler', tip: 'Onluğa tamamla, ikiye katla veya kolay parçalara ayır.' },
  'Sayı Yürüyüşü': { goal: 'Bedenleşmiş Aritmetik (Embodied Arithmetic)', tip: 'Sayı doğrusunda fiziksel olarak yürü! Toplama = ileri, çıkarma = geri. Link ve ark. (2013) bu yöntemin toplama performansını artırdığını gösterdi.' },
  'Bölüşme Zamanı': { goal: 'Bölme Kavramı (Eşit Paylaştırma)', tip: 'Toplam miktarı eşit gruplara ayırmayı düşün.' },
  'Sayı Bağları': { goal: 'Sayı Ayrıştırma (Number Bonds)', tip: 'Bir sayıyı iki parçaya ayır. Parçaların toplamı bütüne eşit olmalı. Örn: 7 = 3+4 = 2+5 = 1+6. Butterworth ve ark. (2011) bu becerinin diskalkuli müdahalesinde temel olduğunu gösterdi.' },
  'Çıkarma Stratejileri': { goal: 'Esnek Çıkarma Stratejileri', tip: 'Farklı stratejiler dene: geriye sayma, onluğa tamamlama veya toplama ile kontrol. Bir strateji zorsa başkasını dene!' },
  'Nokta Karşılaştırma': { goal: 'Yaklaşık Sayı Sistemi (YSS/ANS)', tip: 'Saymadan, sezgisel olarak hangisinde daha çok olduğunu hisset. Bu beceri doğuştan gelen sayı hissinin temelidir (Halberda ve ark., 2008). Weber oranı küçüldükçe zorluk artar.' },
  'Sayı Ayrıştırma': { goal: 'Kavramsal Sanbil (Conceptual Subitizing)', tip: 'Büyük kümeleri küçük alt gruplara böl! 8 noktayı 5+3 veya 4+4 olarak görmeyi dene. MacDonald-Wilkins modelinde bu en üst sanbil düzeyidir.' },
  'Geri Sayma': { goal: 'Geriye Sayma (Ordinalite)', tip: 'Sayı doğrusunda geriye doğru git. Her adımda bir önceki sayıyı düşün. Geri sayma, çıkarma işleminin temelidir.' },
  'Çarpma Kavramı': { goal: 'Tekrarlı Toplama (Çarpma Temeli)', tip: 'Eşit grupları say! 3 grup 4 nesne = 4+4+4 = 12. Çarpma, tekrarlı toplamanın kısa yoludur.' },
  'Sayısal Bellek': { goal: 'Çalışma Belleği (N-Geri Görevi)', tip: 'Gösterilen sayıyı hatırla ve bir/iki öncekiyle karşılaştır. Çalışma belleği matematik becerisinin temelidir (Soltanlou ve ark., 2022).' },
  'Sayısal Stroop': { goal: 'İnhibisyon (Sayısal Stroop Etkisi)', tip: 'Sayının boyutuna aldanma! Fiziksel büyüklük değil, sayısal değer önemli. Otomatik tepkiyi baskıla ve doğru değere odaklan.' },
  'Görev Değiştirme': { goal: 'Bilişsel Esneklik (Task Switching)', tip: 'Kural değişiyor! Toplama ve çıkarma arasında hızlıca geçiş yap. Geçiş maliyetini azaltmak için kuralı her seferinde oku.' },
};
